version: "3.9"

networks:
  cloud-admin-network:

volumes:
  mysql:
  redis:
  rabbitmq:

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    networks:
      - cloud-admin-network
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"


  mysql:
    image: mysql:5.7
    networks:
      - cloud-admin-network
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./cloud-admin.sql:/docker-entrypoint-initdb.d/cloud-admin.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=mongs123"
      - "MYSQL_DATABASE=cloud_admin"

  redis:
    image: redis:5.0
    networks:
      - cloud-admin-network
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command:
      redis-server --requirepass mongs123

  cloud-admin:
    image: cloud-admin:1.0-SNAPSHOT
    ports:
      - "20080:20080"
    depends_on:
      - mysql
      - nacos
      - redis

  cloud-category:
    image: cloud-category:1.0-SNAPSHOT
    ports:
      - "20081:20081"
    depends_on:
      - mysql
      - nacos
      - redis

  cloud-gateway:
    image: cloud-gateway:1.0-SNAPSHOT
    ports:
      - "20050:20050"
    depends_on:
      - mysql
      - nacos
      - redis

  cloud-user:
    image: cloud-user:1.0-SNAPSHOT
    ports:
      - "20082:20082"
    depends_on:
      - mysql
      - nacos
      - redis

  cloud-video:
    image: cloud-video:1.0-SNAPSHOT
    ports:
      - "20083:20083"
    depends_on:
      - mysql
      - nacos
      - redis
