spring:
  cloud:
    gateway:
      routes:
        - id: admin-router
          uri: lb://cloud-admin
          predicates:
            - Path=/admin/**
        - id: category-router
          uri: lb://cloud-category
          predicates:
            - Path=/category/**
        - id: user-router
          uri: lb://cloud-user
          predicates:
            - Path=/user/**
        - id: video-router
          uri: lb://cloud-video
          predicates:
            - Path=/video/**
